### ISSUE TITLE
Does not support SegmentTemplating for BBB mpd file

### ISSUE THREAD

**Issue by tcinbis** [uccmisl/godash#1]
Hello everyone!

First of all, thanks for open sourcing your project. I wanted to try running your code but with an alternative video source. 
I selected the well-known `Big Buck Bunny` video which is also used as an example for the DASH reference player [here](https://reference.dashif.org/dash.js/v3.0.0/samples/dash-if-reference-player/index.html).

I noticed when trying to load the [MPD file](https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd) that the code does not replace placeholder variables before making the request. 
This leads to the following log lines:

```
DEBUG: 2021/07/19 18:21:24 current URL header: https://colasloth.com:8001/bbb_30fps.mpd
DEBUG: 2021/07/19 18:21:24 get file from URL: https://colasloth.com:8001/$RepresentationID$/$RepresentationID$_0.m4v

DEBUG: 2021/07/19 18:21:24 Get the url https://colasloth.com:8001/$RepresentationID$/$RepresentationID$_0.m4v
DEBUG: 2021/07/19 18:21:24 get the rtt https://colasloth.com:8001/$RepresentationID$/$RepresentationID$_0.m4v
DEBUG: 2021/07/19 18:21:24 URL is : https://colasloth.com:8001/$RepresentationID$/$RepresentationID$_0.m4v
DEBUG: 2021/07/19 18:21:24 Protocol is : HTTP/3
DEBUG: 2021/07/19 18:21:24 The URL returned a non status okay error code: 404
```

I was wondering whether there is a simple way to add support for this type of MPD file. 
If so I appreciate any pointers and I am willing to send you PR which implements this. 

Thanks in advance!

**Comment by jq5** [comment]
Hi Tom,

hope all is well and thanks for the message.

godash works for 5 DASH profiles and unfortunately "urn:hbbtv:dash:profile:isoff-live:2012" is not one of those.

I would get the sense it is relatively easy to add this to the list of supported profiles.

the mpd you sent, is both "urn:hbbtv:dash:profile:isoff-live:2012" and "urn:mpeg:dash:profile:isoff-live:2011" and we support isoff-live:2011

one easy way to do this is add some checks in the godash code.

Take mpdParsing.go - line 942

repRateBaseURL = mpd.Periods[0].AdaptationSet[currentMPDRepAdaptSet].Representation[(SegQUALITY)].SegmentTemplate.Media

here we get the base url - once retrieved, you can add a check for "$$" and then add code to replace the placeholder with the actual values.

we actually do a little bit of this already for the isoff-live:2011 profile where we replace $Number$

line 951 - return strings.Replace(repRateBaseURL, "$Number$", nb, -1)

you can see this is the debug values you see at the end of your output "_0.m4v"


Quick question, is the https://colasloth.com:8001/bbb_30fps.mpd an internal server?  I see your using QUIC :)


Please let me know how you get on,

J

**Comment by tcinbis** [comment]
Hey @jq5,
thanks for the super quick reply! I will let you know how I proceed when I come back to this in a few days.

I use colasloth just for local development, you can check [this page](https://colasloth.github.io/) for more information.
Props to @xoudini

**Comment by jq5** [comment]
Cool. Something new to play with 👍

**Comment by ripalx9173** [comment]
Hi I have installed goDash application and i am trying to run it using Virtual box. But when i am trying to lunch it i am running below command to lunch the application i am getting error "bash: /.godash: no such file or directory found. 
./godash -url "[http://cs1dev.ucc.ie/misl/4K_non_copyright_dataset/2_se
c/x265/bbb/DASH_Files/main_byte_range/bbb_enc_x265_dash.mpd]" -adapt conventional -codec h265 -initBuffer 2 -maxBuffer 20 -maxHeight 1080 -streamDuration 10 -storeDASH on -debug on -terminalPrint on -outputFolder "123456" -logFile "log_file_2"

I am new to linux as well as new to this field I want to use this application for one of my university assignment so can you please help me resolve this issue.I have installed this application using all the instructions motioned in readme field. I am attaching screenshot for the same error.
<img width="376" alt="goDash_error" src="https://user-images.githubusercontent.com/36918145/145684579-7e42095e-31e8-493a-b227-7d4f79b8e637.PNG">
 I want to run this application and the sample data you have used. If you can connect over zoom session to help me with it let me know I will share my zoom meeting invite also.
Thank you so much

**Comment by tcinbis** [comment]
Hey @ripalx9173,

From what you wrote I think you first have to compile godash so that you have the godash executable. For this you will have to install the programming language Go and it’s tools. A simple Google search should help you with that. 

Good luck!

**Comment by tcinbis** [comment]
Also closing this issue since I haven’t had the time recently to implement the previously mentioned change and it is more of an feature request than a bug.

**Comment by ripalx9173** [comment]
Hi Tom,
Thank you so much for the quick response. I made the file
install_v1.0.21_ubuntu_20.04.sh
<http://cs1dev.ucc.ie/misl/godash2.0/install_v1.0.21_ubuntu_20.04.sh>So I
have followed the below approach to install the go in my virtual box.

Steps for godash/godashbed install, via install script (tested on Ubuntu 20.04)

The installation of godash/godashbed is best suited to a clean new
installation of Ubuntu, either natively or in a VM.

1.	make the installation script executable:

chmod +x <script.sh>

2.	to get the help screen, just call 'help'

./<script.sh> help

3.	run script:

to run the install script, either call, to install just godash

./<script.sh> goDASH

or call, to install both godash and godashbed

./<script.sh> all

So do I still need to install go in my VM? or is there any other
approach out there?
I am very new to Linux. This is the first time I am using it. So I might be
asking you some basic questions. But if you can help me with it will be
really helpful as my deadline for this assignment is on wednesday.

Regards,
Ripal Patel
