### ISSUE TITLE
Not able to launch the app

### ISSUE THREAD

**Issue by ripalx9173** [uccmisl/godash#3]
Hi Team,
I have followed below steps to install this application using VM in my laptop. I have installed it using install script  and i have followed below commands.
1.Made the installation script executable:
chmod +x install_v1.0.21_ubuntu_20.04.sh
2.to install both godash and godashbed
./install_v1.0.21_ubuntu_20.04.sh all

After that i am trying to launch application using below example
./godash -url "[http://cs1dev.ucc.ie/misl/4K_non_copyright_dataset/2_se
c/x265/bbb/DASH_Files/main_byte_range/bbb_enc_x265_dash.mpd]" -adapt conventional -codec h265 -initBuffer 2 -maxBuffer 20 -maxHeight 1080 -streamDuration 10 -storeDASH on -debug on -terminalPrint on -outputFolder "123456" -logFile "log_file_2"

Here i am getting error saying "bash: /.godash: no such file or directory found. Can you help me with this like where can i find this application? I am not able to find it in bin folder also.
below is the screenshot for the same.
<img width="385" alt="go_2" src="https://user-images.githubusercontent.com/36918145/145685975-fee4f48c-bad5-472f-ad7e-ccae3d6d743e.PNG">

If you can help me understand where i need to execute above command to lunch the example may be i will be able to procced further. If if i have missed any command or any software installation then also please guide me.
@jq5 @roci2015

**Comment by jq5** [comment]
Hi there

a few things to watch out for

1. make sure you are installing from the newest install script 
2. Once everything installs you should have a folder structure that includes a folder called godash 
3. in this folder is the executable ./goDASH
4. It’s easier to use the config file rather than the long terminal command
5. The first thing to do is go to this repo and search for tags and find the highest tag number and load that version
6. The README should update and you can see the easier ways to build and run goDASH
7. It also might be easier to try and just install goDASH on its own to make sure everything’s working before trying to install all
8. Hope this helps, if not come back let me know how you get on

J

**Comment by jq5** [comment]
Hi there

also make sure you are using this newer version of the install script. You will find it on the same website

http://cs1dev.ucc.ie/misl/godash2.0/install_v1.0.22_ubuntu_20.04.sh

also what assignment are you using our code for?

J

**Comment by ripalx9173** [comment]
Hi There,
Thank you so much for the quick response . I am putting my Requirement here you might can help me. So i need Show how we can use Quick protocol is dash video streaming. I am not exactly planning to use your Code. But i need to simulate one sample data using your application and i need to create graph for that result.  So i came across this application and thought i will install this application and try to see result for the example which you have given.
I have done below things till now. 
1. I have installed latest application using install file  
"install_v1.0.22_ubuntu_20.04.sh". 
As per your comments i have navigated to godash folder and listed below files as shown in screenshot
<img width="377" alt="godash_3" src="https://user-images.githubusercontent.com/36918145/145688272-d3f878ea-2ada-473b-b200-f018e9164111.PNG">
I am trying to execute below commands
./goDASH
<img width="402" alt="g0dash_4" src="https://user-images.githubusercontent.com/36918145/145688333-71c2e726-604d-4c84-9a6e-9a5d236845ff.PNG">
But it is giving error as mentioned in screenshot.
Can you help me here. 
Couple questions.
As per read me file i need to install google go  and Install [consul] right? as i have installed application using  installation file.

 I would like to contribute in this project if i will run this application with your guidance and will be able to finish my assignment then i will create user manual with sept by step guide so that anyone who is not having enough knowledge on linux or on go can just read the instruction will be able to use this application if that is ok. Let me know if you can help me with this application installation and simulation over zoom session.
@jq5 @roci2015 

Regards,
Ripal

**Comment by jq5** [comment]
From the screen shot you haven’t installed golang. You only need consul if you using collaborative players…

This might not be your only problem…

what version of Ubuntu are you using?

What is the output when you run the script?

**Comment by ripalx9173** [comment]
Hi There,
I have installed ubuntu-20.04.3-desktop-amd64 version. And after installing the script I have received below output.
![WhatsApp Image 2021-12-11 at 9 57 50 PM](https://user-images.githubusercontent.com/36918145/145689557-c64b42d6-0c21-448e-8e00-6f30ef1c07ec.jpeg)
If possible would you mind sharing your time zone and your email id so that I can communicate over email and then i will update final comments here on this thread. So that it can help me to collaborate with you. I will try to follow below steps tomorrow. But i doubt this will work as i removed this script 2 to 3 times and performed above steps 2 to 3 times and every time i am facing the same issue.

What is the output when you run the script?
It might be best to run the script with the remove option
make sure to use the same script version that you installed with and then maybe just install goDASH on its own first.
@jq5 @roci2015 
Regards,
Ripal

**Comment by jq5** [comment]
I’m only seeing the end of the output. You need to read over all of the output

for now run the script with remove. This will remove all of the folders in your download folder and allow you to start from the beginning again. It’s not enough to remove the script you need to remove the dependencies that were also installed

then start again. But just try and install goDASH on its own

you could also try and install without the script

look at the README me for the highest tag number and follows the install steps for building without the install script

begin with goDASH and see if you can get that to work 

If you get that working you can always build from there

this is the best way to contact us

j

**Comment by ripalx9173** [comment]
Hi There,
Sure will try to follow your instructions and will update you with my progress tomorrow but if possible would you mind sharing simulation result for below sample.
Sample : http://cs1dev.ucc.ie/misl/4K_non_copyright_dataset/4_sec/x264/bbb/DASH_Files/full/bbb_enc_x264_dash.mpd
Regards,
Ripal

**Comment by jq5** [comment]
The link is just the dash MPD file.  Unless you have goDASHbed running it won’t produce quic logs.  Only tcp logs. 

Quick question. Do you know how to use dockers?

If yes

take a look at this link 

https://giters.com/uccmisl/godash/issues/2

and follow the instruction to down load a docker containing godash 

hope this helps

j

**Comment by ripalx9173** [comment]
Hey there ,
I dont know how to use docker i tried to understand the second issue which
you have given me for reference but i dont know docker so bit diffucult.
One quick question if i want to follow docker approach then can you tell me
do i need to use docker inside linux or i can use this application on
windows using docker approach ?
Second things if tomorrow you have free slot can we connect over zoom
session ? I really want to undestnad atleast how to run this application as
i have chosen this topic .I know it will be too much to ask but i am really
new in this area and want to learn it so if connecting over zoom session is
feasible for you let me know your availability or your thoughts on this.

Regards,
Ripal

**Comment by jq5** [comment]
unfortunately connecting over zoom is not possible.

dockers run on windows, so you can use dockers on windows.

as stated go back to basics.. install godash in a new folder from GitHub.  do not use the script, build from the instructions on the README.

take a look here, these web based players might help you get some results you can use.

http://reference.dashif.org/dash.js/latest/samples/

J

**Comment by ripalx9173** [comment]
Hi There,
thank you i think i can follow this docker approach. Can you please confirm my approach.
So first i need to install docker which is done.
Second one docker is done i need to execute below commands right?
1.docker run -it jjq52021/godash
2.docker exec -it ${docker_godash_client} ./godash --config /godash/config/configure.json"  

is it correct? or i am missing anything?

Regards,
Ripal PAtel

**Comment by jq5** [comment]
so 2 things:

1. godash the executable is in a folder called godash.  so no making the folder executable.  look in the config folder, and you will see configure.json - which is a file containing the parameters you were using in the longer terminal call
2. as for docker:

1.docker run --name godash-client -it jjq52021/godash
2.docker exec -it godash-client ./godash --config /godash/config/configure.json"

that should produce some output for you.

you may need to get this from the docker client.  if yes, then in a new terminal windows write:
docker attach godash-client - this will open the docker in the terminal window

do some 'ls' to find godash, then cd to the godash folder and you should find the log output in a folder called "347985" or in whichever folder is defined within the configure.json file under the "storeDash" value.

J

**Comment by jq5** [comment]
so 2 things:

1. godash the executable is in a folder called godash.  so no making the folder executable.  look in the config folder, and you will see configure.json - which is a file containing the parameters you were using in the longer terminal call
2. as for docker:

1.docker run --name godash-client -it jjq52021/godash
2.docker exec -it godash-client ./godash --config /godash/config/configure.json"

that should produce some output for you.

you may need to get this from the docker client.  if yes, then in a new terminal windows write:
docker attach godash-client - this will open the docker in the terminal window

do some 'ls' to find godash, then cd to the godash folder and you should find the log output in a folder called "347985" or in whichever folder is defined within the configure.json file under the "storeDash" value.

J
