### ISSUE TITLE
Error parsing mpd file 

### ISSUE THREAD

**Issue by massimo-gollo** [uccmisl/godash#4]
Hi everyone!
First of all congrats for the project and thank you. 

I'm using your mpdParsing in my code to simplify a bit the process of stream a mpd videofile. Doing this, i started to test godash with my mpd files and i notice (maybe) a bug during parsing of the manifest

Example of manifest: 
`http://staging.massimogollo.it/videofiles/6233ac07a890ed67d7f8cb43/video.mpd`

I suppose the problem is in struct 
```
// AdaptationSet in MPD
type AdaptationSet struct {
        .....
	FrameRate int    `xml:"frameRate,attr"`
	 ....
}
```
In my manifest, `frameRate` attribute is expressed in fraction `30/1`
This bring to fail parsing of entire AdaptionSet and continue to execute godash (or parsing process)

I was wondering if there is simple way to solve this.
Thank you in advance!

**Comment by jq5** [comment]
Hi Massimo,

Happy to hear you are using the project.

Our code works for standard mpd files as detailed in the README, so I started by looking at the structure of your mpd file.

our code does not have "ServiceDescription" or "SegmentTimeline", but that's easy to add.
you also have frameRate in the AdaptationSet, when its typically seen in the Representation.

What did you use to build your video segments and MPD file?

One other item also jumps out.

Your second "AdaptationSet" has no "Representation", in that there is no definition for the bandwidth, codecs, id, mimeType, etc.
<AdaptationSet id="1" contentType="audio" startWithSAP="1" segmentAlignment="true" bitstreamSwitching="true">
</AdaptationSet>

So, maybe go back to the beginning, re-build your segments and the mpd and recheck against our code.

Let me know how you get on,

J

oh, as for the 30/1 just change the 
"FrameRate int    `xml:"frameRate,attr"`" 
to 
"FrameRate string    `xml:"frameRate,attr"`"

that should fix that problem.  if needed, you can always cast to int once the unmarshalling has completed.

**Comment by massimo-gollo** [comment]
Thank you for your quick reply!

```
What did you use to build your video segments and MPD file?
```
i used ffmpeg script to take an mp4 file and convert in dash. Really, the real format of videofiles encoded in mpd doesn't matter for my purpose. My goal is to write a load-generator that get a videolist and, concurrently, reproduce videos. Kind of simulating client that requests videos. So, i would like to godash to stress my video-system and monitoring bandwidth and other parameters of the system. 

Meanwhile could be interesting catch just few metrics from client (godash reproduction) based on the entire streaming session (instead per chunks) 

Since the frameRate could be in kind of "ratio" format, i was thinking to implement somethink like 
```
// AdaptationSet in MPD
type AdaptationSet struct {
....
	FrameRate CustomFrameRate `xml:"frameRate,attr"`
....
}

type CustomFrameRate float64
func (s *CustomFrameRate) UnmarshalXMLAttr(attr xml.Attr) error {
	fmt.Printf("Parsing attribute '%s', with value '%s'", attr.Name.Local, attr.Value)
	tp := strings.Split(attr.Value, "/")
	num,_ := strconv.Atoi(tp[0])
	den,_ := strconv.Atoi(tp[1])
	if den != 0 {
		*s = CustomFrameRate(num/den)
	} else {
		*s = CustomFrameRate(float64(num))
	}

	return nil
}
```
About second AdaptationSet, I check if is empty  and skip to avoid error throwing

```
		if len(mpdList[i].Periods[0].AdaptationSet[j].Representation) == 0{
				break
			}
```

Despite this "fix", my issue changed in error

` *** Problem with converting segment minutes to int ***`
and i didn't catch the error yet 

Thank you

**Comment by jq5** [comment]
When I looked at the issue first, I had to rewrite a few of the structs in mpdParsing, to catch the different structure of your mpd file.  Now that you are changing code, I won't be able find the error, unless I change my code to match your code.

I would propose you change your mechanism for creating the mpd content.

I have used GPAC for all of my dash datasets, and its super easy to use.

Do a search for "gpac creating dash content" or check out this tutorial:
[gpac creating dash content](https://github.com/gpac/gpac/wiki/DASH-basics)

if you can create an MPD that matches the godash structure, you don't need to change code :)

these are our DASH datasets (AVC/HEVC and 4K):
https://www.ucc.ie/en/misl/research/datasets/ivid_dataset/
https://www.ucc.ie/en/misl/research/datasets/ivid_uhd_dataset/

Take a look at the structures of the various DASH profiles and it might help...

Hope this helps, 

J

**Comment by jq5** [comment]
as for the minute problem.  my code assume a few minutes of content, not seconds

do search for "s := strings.Split(streamDuration, "M")"

and wrap his in "if strings.Contains(streamDurationHMS, "M") {"

the same test I do for the hours select.

That should fix the "Problem with converting segment minutes to int" issue

J

**Comment by jq5** [comment]
I rewrote the SplitMPDSegmentDuration function - it works now irrespective of the clip duration (hours, minutes, seconds or any combination)

func SplitMPDSegmentDuration(mpdSegDuration string) int {

	var totalTimeinSeconds int
	var streamDuration string

	// lets first determine the length of the file
	// remove the "PT"
	streamDurationHMS := strings.Replace(mpdSegDuration, "PT", "", -1)

	// if streamDurationHMS contains hours
	if strings.Contains(streamDurationHMS, "H") {
		// get the hours
		H := strings.Split(streamDurationHMS, "H")
		streamDurationH := H[0]
		// if there are hours, convert to seconds
		i3, err := strconv.Atoi(streamDurationH)
		if err != nil {
			fmt.Println("*** Problem with converting segment hours to int ***")
			// stop the app
			utils.StopApp()
		}
		if i3 > 0 {
			totalTimeinSeconds += i3 * 60 * 60
		}
		streamDuration = H[1]
	} else {

		// remove the "PT0H"
		// this can't contain PT0H, as H was not found in the if check
		// streamDuration = strings.Replace(mpdSegDuration, "PT0H", "", -1)
		// PT feels better
		streamDuration = strings.Replace(mpdSegDuration, "PT", "", -1)
	}

	// split around the Minutes
	if strings.Contains(streamDuration, "M") {

		m := strings.Split(streamDuration, "M")

		// if there are minutes, convert to seconds
		i1, err := strconv.Atoi(m[0])
		if err != nil {
			fmt.Println("*** Problem with converting segment minutes to int ***")
			// stop the app
			utils.StopApp()
		}
		if i1 > 0 {
			totalTimeinSeconds += i1 * 60
		}
		// get the seconds and convert to int
		streamDuration = m[1]
	} 

	// split around the Seconds
	if strings.Contains(streamDuration, "S") {

		// get the seconds and convert to int
		s := strings.Split(streamDuration, ".")
		i2, err := strconv.Atoi(s[0])
		if err != nil {
			fmt.Println("*** Problem with converting segment seconds to int ***")
		}
		if i2 > 0 {
			totalTimeinSeconds += i2
		}
	}

	// return the minutes and seconds (in seconds)
	return totalTimeinSeconds

**Comment by massimo-gollo** [comment]
> When I looked at the issue first, I had to rewrite a few of the structs in mpdParsing, to catch the different structure of your mpd file. Now that you are changing code, I won't be able find the error, unless I change my code to match your code.
> 
> I would propose you change your mechanism for creating the mpd content.
> 
> I have used GPAC for all of my dash datasets, and its super easy to use.
> 
> Do a search for "gpac creating dash content" or check out this tutorial: [gpac creating dash content](https://github.com/gpac/gpac/wiki/DASH-basics)
> 
> if you can create an MPD that matches the godash structure, you don't need to change code :)
> 
> these are our DASH datasets (AVC/HEVC and 4K): https://www.ucc.ie/en/misl/research/datasets/ivid_dataset/ https://www.ucc.ie/en/misl/research/datasets/ivid_uhd_dataset/
> 
> Take a look at the structures of the various DASH profiles and it might help...
> 
> Hope this helps,
> 
> J

I'm sorry, i did not want to change you code explicitly to my specific problem (and specific mpd). Rather i would expand and generalize, covering multiple situation. Thank you for you help and your time spent 

The orginal issue was related to unmarshal of xml field `frameRate`. In you code it's an `int` but it could be a float, but it's negligible, i think. The second one (related to duration) maybe it's more relevant. 

Thank you so much for both code and gpac documentation! i'll test ASAP

**Comment by jq5** [comment]
and thank you for the help.  It's always nice to find the edge cases in the code :)

as for your MPD, godash currently covers a range of the standard MPDs but not all of the MPDs available.

So, its always good to add to the "mpdParsing" code.

I'll close this issue now, but if you need any more help/advise or find any more issues, just let us know,

Best wishes,

J
