### ISSUE TITLE
Problems encountered by godash when I use the self-config mpeg-dash server based nginx-quic

### ISSUE THREAD

**Issue by NullLimite** [uccmisl/godash#9]
![image](https://github.com/uccmisl/godash/assets/20982456/7dd81b76-0ab6-4b21-8201-814edb025a8f)

**Comment by jq5** [comment]
Hi there,

This seems to be a problem with the config file, can you upload a copy of the config file and we can check on our side.

Best wishes,

J

**Comment by NullLimite** [comment]
Thanks for your response. I use `./godash -config ./config/configure.json` to run my test. Below is the content of my config file.
```
# config/configure.json
{
        "adapt" : "bba",
        "codec" : "h264",
        "debug" : "on",
        "initBuffer" : 4,
        "maxBuffer" : 60,
        "maxHeight" : 1080,
        "streamDuration" : 40,
        "storeDash" : "on",
        "outputFolder" : "123456",
        "logFile" : "log_file_2",
        "getHeaders" : "off",
        "terminalPrint" : "on",
        "printHeader" : "{\"Algorithm\":\"on\",\"Seg_Dur\":\"on\",\"Codec\":\"on\",\"Width\":\"on\",\"Height\":\"on\",\"FPS\":\"on\",\"Play_Pos\":\"on\",\"RTT\":\"on\",\"Seg_Repl\":\"on\",\"Protocol\":\"on\",\"TTFB\":\"on\",\"TTLB\":\"on\",\"P.1203\":\"on\",\"Clae\":\"on\",\"Duanmu\":\"on\",\"Yin\":\"on\",\"Yu\":\"on\"}",
        "expRatio": 0.2,
        "quic" : "off",
        "useTestbed" : "off",
        "url" : "[http://10.21.5.39/bbb_30fps/output/stream.mpd]",
        "QoE" : "on",
        "serveraddr" : "off"
}
```
`"[http://10.21.5.39/bbb_30fps/output/stream.mpd]"` is my self-config MPEG-DASH server, and it can be played in dash.js and Potplayer.

**Comment by jq5** [comment]
The config file works fine for me when I change the url.

I don’t get the error you have.

Understandably, I get an error when I use your url:

There is an issue with the URL parameter - this could be a malformed configuration file, please double check

Try to run godash with this url:

http://cs1dev.ucc.ie/misl/4K_non_copyright_dataset/2_sec/x264/bbb/DASH_Files/full/bbb_enc_x264_dash.mpd 

If this works, then it’s simply that we can’t support that server

If it doesn’t work, then there is a build error in godash on your side.

Let me know,

J

**Comment by NullLimite** [comment]
Oh, I try to run your URL, and it works fine. 

But I don't know why my server is not supported. 

Does `godash` have any requirements for the server?

**Comment by jq5** [comment]
We have tested it on a WSGI server - “Caddy V2” and on a ASGI server - “Hypercorn" for both the TCP and QUIC protocols and both servers work perfectly with godash.

At this stage, I do not foresee any other servers being implemented…


My advise is start printing logs on your server side, and try and see where the issue is...

Best wishes,

J

**Comment by NullLimite** [comment]
I also want to retest using “Caddy V2“. Could you please share your `Caddyfile` with me?

**Comment by jq5** [comment]
Do a search on GitHub for goDASHbed and that contains all the config files for the servers mentioned earlierHave funJSent from my iPhoneOn 12 Sep 2023, at 7:23 a.m., AIRCode ***@***.***> wrote:﻿
I also want to retest using “Caddy V2“. Could you please share your Caddyfile with me?

**Comment by NullLimite** [comment]
Thank you very much, I will try it right away

**Comment by NullLimite** [comment]
Hi, I found a solution to my problem. When I used `MP4Box -profile simple` instead of `Bento4`, the problem disappeared. So the root cause is the way MPEG-DASH videos are generated, which means that `godash` cannot parse all types of MPD files.

I previously used `Bento4`(`mp4fragment`, `mp4dash`) to generate MPEG-DASH video. The MPD file looks like this:
<img width="907" alt="Snipaste_2023-09-13_09-31-54" src="https://github.com/uccmisl/godash/assets/20982456/d2a629fb-1fc6-4dcf-8c62-98844ceecac2">

Below is a screenshot of the packet I captured using `tcpdump`:
<img width="984" alt="mp4dash" src="https://github.com/uccmisl/godash/assets/20982456/ebabc5c2-5dc1-4ebe-9fa3-8b6f7db0691a">

It can be seen from this that after `godash` parsed the MPD file generated by `Bento4`, it did not replace `$RepresentationID$` during the http request, so a `404` error occurred.
<img width="553" alt="Snipaste_2023-09-13_09-51-37" src="https://github.com/uccmisl/godash/assets/20982456/d49e13c4-6f35-4985-81bf-a2238e675510">

When I changed to using `MP4Box -profile onDemand`, the following problems occurred:
<img width="454" alt="onDemand" src="https://github.com/uccmisl/godash/assets/20982456/14dc5464-36c3-48a8-8022-343cceff345a">

When I use `MP4Box -profile [simple,main,full]` instead, the MPD file looks like this:
<img width="976" alt="Snipaste_2023-09-13_09-33-24" src="https://github.com/uccmisl/godash/assets/20982456/e427741c-884f-48d9-ba51-7b8c7e820571">

At this point, use `tcpdump` to capture a screenshot of the packet:
<img width="984" alt="simple" src="https://github.com/uccmisl/godash/assets/20982456/150eb5e0-77e2-493e-a75e-59970117bd79">

As mentioned above, `godash` currently only supports MPD files generated by `MP4Box -profile [simple,main,full]`.

**Comment by jq5** [comment]
First off, it’s great that you found the solution, and it was not godash, well kind of :)

It’s important to remember that godash is a few years old now, and newer software can change over time, and cause issues in my little friend…

That said, this is a DASH dataset we created with MP4Box to test godash on:

https://www.ucc.ie/en/misl/research/datasets/ivid_uhd_dataset/

It contains the full, main, live, full byte range, main byte range and “onDemand" byte range DASH profiles for AVC and HEVC up to UHD/4K.

So godash has not been tested on simple, but it good to see that it works with simple, if created with MP4Box, which is the software that we used to create the datasets...

Again, great to see you found a solution

Best wishes,

J
